- title: Configuring Ballerina programs
  url: '#'
  sublinks:
    - title: Quick start on using configurable variables
      url: /learn/configuring-ballerina-programs/quick-start-on-configurable-variables
      sublinks:
        - title: Configuring a sample Ballerina service
          url: /learn/configuring-ballerina-programs/quick-start-on-configurable-variables/#configuring-a-sample-ballerina-service
          active: configuring-a-sample-ballerina-service
    - title: Providing values to configurable variables
      url: /learn/configuring-ballerina-programs/providing-values-to-configurable-variables
      sublinks:
        - title: Providing configuration values through command-line arguments
          url: /learn/configuring-ballerina-programs/providing-values-to-configurable-variables/#providing-configuration-values-through-command-line-arguments
          active: providing-values-through-command-line-arguments
        - title: Providing configuration values through TOML syntax
          url: /learn/configuring-ballerina-programs/providing-values-to-configurable-variables/#providing-configuration-values-through-toml-syntax
          active: providing-configuration-values-through-toml-syntax
        - title: Providing module information of the configurable variable
          url: /learn/configuring-ballerina-programs/providing-values-to-configurable-variables/#providing-module-information-of-the-configurable-variable
          active: providing-module-info-of-configurable-variable
    - title: Configuring values in Kubernetes environments
      url: /learn/configuring-ballerina-programs/configuring-values-in-kubernetes-environment/
      sublinks:
        - title: Securing sensitive data using configurable variables
          url: /learn/configuring-ballerina-programs/configuring-values-in-kubernetes-environment/#securing-sensitive-data-using-configurable-variables
          active: securing-sensitive-data-using-configurable-variables
